name: Build
on: [pull_request]

env:
    PR: ${{ toJson(github.event.pull_request) }}

jobs:
    build:
        name: Build packages
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo ${{ env.PR }}
