name: Build
on: [pull_request]

jobs:
    build:
        name: Build packages
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo ${{ github.event.pull_request }}
