name: Release
on: [pull_request]

jobs:
    changeset:
        runs-on: ubuntu-latest
        name: changeset
        env:
            TURBO_RUN_FILTER: ${{ github.event_name == 'pull_request' && '...[origin/main]' || '...[HEAD^]' }}
        outputs:
            packages: ${{ steps.changeset.outputs.result }}
        steps:
            - id: changeset
              run: |
                content='["docs", "web"]''
                echo "::set-output name=result::$content"
    
    build:
        runs-on: ubuntu-latest
        name: ${{ matrix }} build
        if: needs.changeset.outputs.packages != ''
        needs: ["changeset"]
        strategy:
            fail-fast: false
            matrix:
                include: ${{fromJson(needs.changeset.outputs.packages)}}
        steps:
            - run: echo ${{matrix}}
