name: Release
on: [pull_request]

jobs:
    changeset:
        runs-on: ubuntu-latest
        name: changeset
        defaults:
            run:
              working-directory: ./scripts
        env:
            TURBO_RUN_FILTER: ${{ github.event_name == 'pull_request' && '...[origin/main]' || '...[HEAD^]' }}
        outputs:
            packages: ${{ steps.changeset.outputs.result }}
        steps:
            - name: Determine changed apps
              run: |
                content=./find-changesets.js
                echo $content
                echo "result=$content" >> $GITHUB_OUTPUT
    
    build:
        runs-on: ubuntu-latest
        name: build
        needs: ["changeset"]
        # strategy:
        #     fail-fast: false
        #     matrix:
        #         include: ${{fromJson(needs.changeset.outputs.packages)}}
        steps:
            - run: echo "packages ${{needs.changeset.outputs.packages}}"
