name: Release
on: [pull_request]

jobs:
    changeset:
        runs-on: ubuntu-latest
        name: changeset
        env:
            TURBO_RUN_FILTER: ${{ github.event_name == 'pull_request' && '...[origin/main]' || '...[HEAD^]' }}
        outputs:
            packages: ${{ steps.changeset.outputs.result }}
        steps:
            - name: Check out code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Install Node.js
              uses: actions/setup-node@v3
            - name: Install pnpm
              uses: pnpm/action-setup@v2
            - name: Determine changed apps
              id: changeset
              run: |
                echo "result=$(./scripts/find-changesets.js)" >> $GITHUB_OUTPUT
    
    build:
        runs-on: ubuntu-latest
        name: build
        needs: ["changeset"]
        # strategy:
        #     fail-fast: false
        #     matrix:
        #         include: ${{fromJson(needs.changeset.outputs.packages)}}
        steps:
            - run: echo "packages ${{needs.changeset.outputs.packages}}"
