name: Release
on: [pull_request]

jobs:
    changeset:
        runs-on: ubuntu-latest
        name: changeset
        env:
            TURBO_RUN_FILTER: ${{ github.event_name == 'pull_request' && '...[origin/main]' || '...[HEAD^]' }}
        outputs:
            packages: ${{ steps.changeset.outputs.result }}
        steps:
            - id: changeset
              run: ./scripts/find-changesets.js
    
    build:
        runs-on: ubuntu-latest
        name: build
        needs: ["changeset"]
        # strategy:
        #     fail-fast: false
        #     matrix:
        #         include: ${{fromJson(needs.changeset.outputs.packages)}}
        steps:
            - run: echo "packages ${{needs.changeset.outputs.packages}}"
